---
title: "First Summative Assessment"
output:
  html_document:
    theme: null
    highlight: null
    css: styles.css
editor_options: 
  markdown: 
    wrap: 72
---

<h1>

THE<br>*MONTY HALL*<br>PROBLEM

</h1>

::: monty-title
<h2>

The Problem

</h2>
:::

<section class="section-plans" id="section-plans">

::: {.u-center-text .u-margin-bottom-big}
:::

::: row
::: col-1-of-3
::: card
::: {.card__side .card__side--front-1}
::: {.card__title .card__title--1}
<i class="fas fa-paper-plane"></i>

<h4 class="card__heading">

DOOR 1 (PLACEHOLDER UNTIL IM DONE MAKING THE GRAPHICS

</h4>
:::
:::

::: {.card__side .card__side--back .card__side--back-1}
::: card__cta
::: card__price-box
placeholder text until im done with the graphics
:::

<a href="#popup" class="btn btn--white">Select</a>
:::
:::
:::
:::

::: col-1-of-3
::: card
::: {.card__side .card__side--front-2}
::: {.card__title .card__title--2}
<i class="fas fa-plane"></i>

<h4 class="card__heading">

DOOR 2 (PLACEHOLDER UNTIL IM DONE MAKING THE GRAPHIC

</h4>
:::
:::

::: {.card__side .card__side--back .card__side--back-2}
::: card__cta
::: card__price-box
placeholder text until im done with the graphics
:::

<a href="#popup" class="btn btn--white">Select</a>
:::
:::
:::
:::

::: col-1-of-3
::: card
::: {.card__side .card__side--front-3}
::: {.card__title .card__title--3}
<i class="fas fa-rocket"></i>

<h4 class="card__heading">

DOOR 3 (PLACEHOLDER UNTIL IM DONE MAKING THE GRAPHIC

</h4>
:::
:::

::: {.card__side .card__side--back .card__side--back-3}
::: card__cta
::: card__price-box
placeholder text until im done with the graphics
:::

<a href="#popup" class="btn btn--white">Select</a>
:::
:::
:::
:::
:::

</section>

::: monty-body
The Monty Hall problem starts with 3 doors. Behind 1 of these doors is a
car, and the other 2 are goats. You pick 1 door of your choice, and then
"Monty" picks one of the unopened doors which is guaranteed to be a
goat. This means that between your door and the other door, one is the
car and the other is the goat. The question is, do you change your door
of choice to the other door or stick to your initial choice? <br> <br>
Interestingly enough, while it may seem like a 50/50 probability, it was
found that changing your door to the other one has a 2/3 probability of
winning. Why is this the case? <br> <br> (insight here) <br> <br>
Initially, let's assume that there is no bias or influence that's
helping us determine which door is likely to be the car or a goat at the
start. This means that each door equally has a 1/3 probability of being
picked. If our first choice is a goat, then switching would result in
the car. On the other hand, if your first choice is the car, then
switching would surely result in a goat. While the odds may seem equal,
take note that we have 2 options for the goat behind the door. This
means that, given we switch doors at the end, we now have 2 doors that
will lead to victory, or essentially a 2/3 chance of winning like
mentioned a while ago. <br> <br> (insight/reaction here)
:::

::: monty-body

</section>

::: monty-body <!--Lotto Section, just used monty hall css formatting-->
The UltraLotto 6/58 is a lottery game wherein the player buys a card for 20 pesos, and picks out 6 numbers ranging from 1-58, wherein a number can only be picked once. The current prizepool is 50 Million Pesos, leading some to believe that buying many cards would give them better chances. This is hardly true as the possibility of getting all 6 numbers correct is so small, specifically 1/40,475,358 such that even buying a few more cards would only add mere fractions of a percentage to that possibility. If we were to calculate how many cards it would take to get all possible combinations of numbers, we would need to purchase 40,475,358 cards, costing us 809,507,160 pesos, which is immensely greater than the 50 million peso prize, thus incurring a massive loss on the bettor.
:::

::: monty-body
<h2>

References

</h2>

<https://mathworld.wolfram.com/MontyHallProblem.html>
<!-- there's details about the citation like the author and date at the bottom of the page so if we cite this in another format then there ya go -->
<br> <https://ysbecca.github.io/random/2017/10/31/monty-hall.html>
:::
